name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install libsfml-dev
    - name: build
      run: ./build.sh

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: brew install sfml
    - name: build
      run: ./build.sh

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup WSL
      uses: Vampire/setup-wsl@v2.0.1
      with:
        distribution: Debian
        additional-packages: libsfml-dev
    - name: build
      shell: wsl-bash {0}
      run: ./build.sh
